### ISSUE TITLE
Username Element Could not be found 

### ISSUE THREAD

**Issue by danishaziz-8** [soos-io/soos-dast#108]
Command ro run authenticated scan:
sudo docker run --network=host -it --rm soosio/dast --clientId=1rm7##@# --apiKey=REWEWDw13323wewedewwefwew3223 --projectName="IRIS" --ajaxSpider "https://example.com:8670/BPCLUSTER5702/" --authLoginURL="https://example.com:8670/BPCLUSTER5702/UserManagement" --authUsernameField=UserName --authUsername=admin --authPasswordField=Password --authPassword=tpstps_321 --scanMode=fullscan

Error :
2024-03-08 01:14:48 PM UTC [INFO] Running ZAP
2024-03-08 01:14:49 PM UTC [INFO] load_config: ['-config', 'spider.maxDuration=0', '-silent']
2024-03-08 01:14:49 PM UTC [INFO] Extra params passed by ZAP: ['-config', 'spider.maxDuration=0', '-silent']
2024-03-08 01:15:06 PM UTC [INFO] zap_started_hook is running
2024-03-08 01:15:06 PM UTC [INFO] Start webdriver
2024-03-08 13:15:06,779 Using default request storage
2024-03-08 13:15:06,802 Created proxy listening on 127.0.0.1:43059
2024-03-08 01:15:11 PM UTC [INFO] authenticate using webdriver against URL: https://example.com:8670/BPCLUSTER5702/UserManagement
2024-03-08 01:15:23 PM UTC [INFO] automatically finding login elements
2024-03-08 01:15:23 PM UTC [INFO] Trying to find element UserName
2024-03-08 01:15:23 PM UTC [INFO] Built xpath: //input[(translate(@id, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')='username') and (@type='text' or @type='email' or @type='number' or not(@type))]
2024-03-08 01:15:23 PM UTC [INFO] Built xpath: //input[(translate(@name, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')='username') and (@type='text' or @type='email' or @type='number' or not(@type))]
2024-03-08 01:15:23 PM UTC [INFO] Failed to find the element UserName
Traceback (most recent call last):
  File "/zap/src/zap_hooks/helpers/auth.py", line 65, in authenticate
    login(driver_instance, config)
  File "/zap/src/zap_hooks/helpers/auth.py", line 198, in login
    username_element = fill_username(config, driver)
  File "/zap/src/zap_hooks/helpers/auth.py", line 259, in fill_username
    return find_and_fill_element(config.auth_username,
  File "/zap/src/zap_hooks/helpers/auth.py", line 288, in find_and_fill_element
    element.clear()

**Comment by SOOS-JAlvarez** [comment]
Hey, sorry about the delay, sometimes the forms are incompatible, we use selenium under the hood to try and find the fields to fill and sometimes it's just not possible.

Apart from making sure than in the url `https://example.com:8670/BPCLUSTER5702/UserManagement` is the form you're trying to access and the ids for the fields match. There's not much we can do in our end (sice it seems its a local hosted web app).

We do support other ways of authentication such as providing a token, headers, cookies and so on, we have all the options available documented in [here](https://kb.soos.io/help/running-dast-with-an-authenticated-user).

If you require additional assistance you can cotact us trough support@soos.io providing the full logs and clientId where we may be able to help you better.

**Comment by SOOS-JAlvarez** [comment]
Closing this issue since it has been inactive for a month now
